### ISSUE TITLE
Example for Authentication

### ISSUE THREAD

**Issue by Swissbite** [ExpediaDotCom/graphql-kotlin#229] opened 2019-05-28 19:47 UTC
I'm struggling with providing a schema based on current user authentication. It would be great to have an example, where the schema and the validation of the request are handled by a simple user role manner.

For simplification, I would use a simple basic authentication handler (which may be the spring security handler) and three different user/roles (anonymous, editor, admin) where the anonymous can only read data, an editor can read and edit basic data and an administrator has some other modification permissions.

My quick and dirty way was using a user aware context and check on the mutation if the current user has sufficient rights to execute it. But every user can see the complete schema.

**Comment by smyrick** [comment] 2019-05-31 22:19
@Swissbite Right now there is not a way I know of to hide parts the schema. Everyone can still seeing the entire schema but you can control who can access specific fields in that manner and using graphql directives too.

 `directive @auth(role : String!) on FIELD_DEFINITION`

Here is an example from the graphql-java docs: https://www.graphql-java.com/documentation/v11/sdl-directives/

**Comment by smyrick** [comment] 2019-05-31 22:20
And another question about auth: https://github.com/ExpediaDotCom/graphql-kotlin/issues/218

**Comment by smyrick** [comment] 2019-05-31 22:21
Duplicate of https://github.com/ExpediaDotCom/graphql-kotlin/issues/218

**Closed by smyrick** 2019-05-31 22:21 UTC
Labels: type: question
